---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 80
ratings:
  paths:
  - "scss/**/*.scss"
  - "src/**/*.js"
exclude_paths:
- src/**/*Impl.js
- www/
- hooks/
- test/
- src/lib/
- src/js/lib
- node_modules/
- gulpfile.js
- karma.conf.js
- protractor.conf.js
- .eslintrc
