---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      exclude_paths: 
      - "src/**/*{mock|Impl}.js"
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "scss/**/*.scss"
  - "src/**/*.js"
exclude_paths:
- hooks/
- test/
- src/lib/
- src/js/lib
- node_modules/
- gulpfile.js
- karma.conf.js
- protractor.conf.js
- .eslintrc
