---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.js"
exclude_paths:
- hooks/
- tests/
- www/lib/
